### ISSUE TITLE
Help debugging "Unsupported CLR type" exceptions

### ISSUE THREAD

**Issue by markhepburn** [ckimes89/graphql-net#51]
I've moved on to testing using a model from an existing project.  This is a code-first model, originally reverse-engineered from the database, if that's relevant.  I was able to successfully run queries if I manually added some fields (ie calling `GraphQLTypeBuilder.AddField()`), but given that we have a fair few models and they're quite large, this isn't ideal.

However, I've encountered issues running a basic example using `AddAllFields()`:

```csharp
var schema = GraphQL<EQContext>.CreateDefaultSchema(() => new EQContext());
schema.AddScalar(new { year = 0, month = 0, day = 0 }, ymd => new DateTime(ymd.year, ymd.month, ymd.day));
schema.AddType<EQ>().AddAllFields();
schema.AddField("eq", new { id = "" }, (db, args) => db.EQs.FirstOrDefault(e => e.EQ_ID == args.id));
schema.Complete();
```

Specifically, `ExecuteQuery` is throwing `GraphQL.Parser.ValidationException: Unsupported CLR type EQ`.

The `EQ` model is mostly `string`, `decimal`, and nullable `DateTime` fields, along with a bunch of references to other models.  Any suggestions for what could be causing this, or how to debug it?

Things I've tried:

* Adding recursive fields to models in the test suite (for example, in `User` I added a `Supervisor`/`DirectReports` many-one pair of fields), to test if that was an issue
* Adding every other model referenced from the model in question (ie, everything in the context) to the schema
* Ensuring that `DateTime` has been added via `schema.AddScalar()`

I'll move on now, but I'd like to add that this is a super promising project, and I'm happy to help out if I can.

**Comment by ckimes89** [comment]
So, this error is being thrown in [TypeHandlers.fs](https://github.com/ckimes89/graphql-net/blob/master/GraphQL.Parser/SchemaTools/TypeHandlers.fs#L59) because of a type resolution failure. It definitely seems like an error since you're defining the EQ type, but the source might be hard to pinpoint.

A few suggestions:

1. Paste the full stack trace of the exception here.
2. Since it seems like you have downloaded the code, place breakpoints on the `this.GetMapping()` calls and see if you can trace through them for more information.
3. Comment out the potentially broken properties in EQ (references to other entities, nullable datetimes) until you can isolate the problem. This will likely still fail if it gets to executing against the database, but that should help identify what is causing the library to break.

**Comment by markhepburn** [comment]
Thanks, I'll do a bit of digging.  This is the stack-trace for now:

```
at GraphQL.Parser.TypeHandlerExtensions.ITypeHandler.VariableTypeOf(ITypeHandler this, Type targetType)
   at <StartupCode$GraphQL-Parser>.$TypeHandlers.fields@328-1.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at <StartupCode$GraphQL-Parser>.$TypeHandlers.fields@326.Invoke(Unit unitVar)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at <StartupCode$GraphQL-Parser>.$TypeHandlers.varType@332.Invoke(Unit unitVar)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at GraphQL.Net.VariableTypes.VariableTypeOf(Type clrType)
   at GraphQL.Net.SchemaAdapters.SchemaField..ctor(ISchemaQueryType`1 declaringType, GraphQLField field, Schema schema)
   at GraphQL.Net.SchemaAdapters.SchemaType.<>c__DisplayClass2_0.<.ctor>b__1(GraphQLField f)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at GraphQL.Net.SchemaAdapters.SchemaType.<>c__DisplayClass2_0.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at GraphQL.Net.SchemaAdapters.SchemaType.get_Fields()
   at GraphQL.Parser.SchemaResolver.Resolver`1.ResolveFieldSelection(Field pfield, SourceInfo pos)
   at GraphQL.Parser.SchemaResolver.Resolver`1.ResolveSelection(Selection pselection, SourceInfo pos)
   at GraphQL.Parser.SchemaResolver.ResolveSelections@228.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at GraphQL.Parser.SchemaResolver.Resolver`1.ResolveSelections(IEnumerable`1 pselections)
   at GraphQL.Parser.SchemaResolver.Resolver`1.ResolveFieldSelection(Field pfield, SourceInfo pos)
   at GraphQL.Parser.SchemaResolver.Resolver`1.ResolveSelection(Selection pselection, SourceInfo pos)
   at GraphQL.Parser.SchemaResolver.ResolveSelections@228.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at GraphQL.Parser.SchemaResolver.Resolver`1.ResolveSelections(IEnumerable`1 pselections)
   at GraphQL.Parser.SchemaResolver.Resolver`1.ResolveOperation(Operation poperation, SourceInfo pos)
   at GraphQL.Parser.SchemaResolver.ResolveOperations@277.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at GraphQL.Parser.GraphQLDocument`1.Parse(ISchema`1 schema, String source)
   at GraphQL.Net.GraphQL`1.ExecuteQuery(String queryStr)
   at PMRTests.UnitTest1.testGraphQL() in C:\Users\mark_2\Projects\utas_campus_services\PMR\PMRTests\UnitTest1.cs:line 77

```

**Comment by markhepburn** [comment]
Actually, I've at least got it working (and back down to a pretty minimalist working test again) thanks to the `this.GetMapping` breakpoint tip.  There was a pretty nasty hack buried in a partial class, that I hadn't noticed before.  I'm pretty sure it's no longer used too, which is encouraging (without going into too many details, it looked something like this: `public EQFields _fields { get { return new EQFields(this); } }`.  I haven't trawled any further, but that's a definite code smell and I'm not surprised it caused problems)

**Comment by markhepburn** [comment]
Given that this issue was a personal question and definitely doesn't look like a library bug, I'll close it off.

If you feel it should have handled it, or want more details just for your own understanding, just reopen and I'll work with you on it.  Thanks for your help.

**Comment by harrisse** [comment]
I ran into the same issue when trying to map a field of type Nullable<DateTime>. Nullable<int> works fine and DateTime works fine but Nullable<DateTime> throws the CLR exception. Do we expect that Nullable<DateTime> typed fields should be mappable?

**Comment by ckimes89** [comment]
Hi harrisse,

Sorry for the delay! I've been pretty busy recently - I probably won't be able to take a close look at this until Sunday. I definitely expect that `Nullable<DateTime>` should work.

Can you provide me with a minimal test case to look at on Sunday? A good place to start would be forking the project and using the in-memory tests at:

https://github.com/ckimes89/graphql-net/blob/master/Tests/InMemoryExecutionTests.cs
and
https://github.com/ckimes89/graphql-net/blob/master/Tests/MemContext.cs

**Comment by harrisse** [comment]
Thanks for the quick response. I'm having a hard time reproducing the issue in your test project, so please don't worry about the issue for now, and I'll let you know if I can get a more reproducible test case.

**Comment by Owlinated** [comment]
Hey there @ckimes89,

Love the library!

I know this is a pretty old issue, but I just ran into it and found a way to reproduce it.
As you suggested I modified the MemContext by adding a Nullable DateTime property to User:
~~~~
    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }

        public int AccountId { get; set; }
        public Account Account { get; set; }

        public int? NullRefId { get; set; }
        public NullRef NullRef { get; set; }

	public DateTime? NullableDate { get; set; }
    }
~~~~

This causes the AddAllFields test to run into this exception:
~~~~
GraphQL.Parser.ValidationException occurred
  HResult=0x80131500
  Message=Unsupported CLR type ``DateTime''
  Source=FSharp.Core
  StackTrace:
   at Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
   at GraphQL.Parser.Utilities.invalid[a](String msg) in C:\Users\<User>\Documents\graphql-net\GraphQL.Parser\Utilities.fs:line 46
   at GraphQL.Parser.TypeHandlerExtensions.ITypeHandler.VariableTypeOf(ITypeHandler this, Type targetType) in C:\Users\<User>\Documents\graphql-net\GraphQL.Parser\SchemaTools\TypeHandlers.fs:line 59
   at GraphQL.Parser.NullableTypeHandler.GraphQL-Parser-ITypeHandler-GetMapping(Type ty) in C:\Users\<User>\Documents\graphql-net\GraphQL.Parser\SchemaTools\TypeHandlers.fs:line 162
   at GraphQL.Parser.ChainTypeHandler.GraphQL-Parser-ITypeHandler-GetMapping(Type targetType) in C:\Users\<User>\Documents\graphql-net\GraphQL.Parser\SchemaTools\TypeHandlers.fs:line 52
   at GraphQL.Parser.ChainTypeHandler.GraphQL-Parser-ITypeHandler-GetMapping(Type targetType) in C:\Users\<User>\Documents\graphql-net\GraphQL.Parser\SchemaTools\TypeHandlers.fs:line 50
   at GraphQL.Parser.ChainTypeHandler.GraphQL-Parser-ITypeHandler-GetMapping(Type targetType) in C:\Users\<User>\Documents\graphql-net\GraphQL.Parser\SchemaTools\TypeHandlers.fs:line 50
   at GraphQL.Parser.ChainTypeHandler.GraphQL-Parser-ITypeHandler-GetMapping(Type targetType) in C:\Users\<User>\Documents\graphql-net\GraphQL.Parser\SchemaTools\TypeHandlers.fs:line 50
   at GraphQL.Parser.ChainTypeHandler.GraphQL-Parser-ITypeHandler-GetMapping(Type targetType) in C:\Users\<User>\Documents\graphql-net\GraphQL.Parser\SchemaTools\TypeHandlers.fs:line 50
   at GraphQL.Parser.ChainTypeHandler.GraphQL-Parser-ITypeHandler-GetMapping(Type targetType) in C:\Users\<User>\Documents\graphql-net\GraphQL.Parser\SchemaTools\TypeHandlers.fs:line 50
   at GraphQL.Parser.RootTypeHandler.GraphQL-Parser-ITypeHandler-GetMapping(Type targetType) in C:\Users\<User>\Documents\graphql-net\GraphQL.Parser\SchemaTools\TypeHandlers.fs:line 512
   at GraphQL.Net.VariableTypes.VariableTypeOf(Type clrType) in C:\Users\<User>\Documents\graphql-net\GraphQL.Net\VariableTypes.cs:line 50
   at GraphQL.Net.SchemaAdapters.SchemaField..ctor(ISchemaQueryType`1 declaringType, GraphQLField field, Schema schema) in C:\Users\<User>\Documents\graphql-net\GraphQL.Net\SchemaAdapters\SchemaField.cs:line 21
   at GraphQL.Net.SchemaAdapters.SchemaType.<>c__DisplayClass2_0.<.ctor>b__1(GraphQLField f) in C:\Users\<User>\Documents\graphql-net\GraphQL.Net\SchemaAdapters\SchemaType.cs:line 18
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at GraphQL.Net.SchemaAdapters.SchemaType.<>c__DisplayClass2_0.<.ctor>b__0() in C:\Users\<User>\Documents\graphql-net\GraphQL.Net\SchemaAdapters\SchemaType.cs:line 17
   at System.Lazy`1.CreateValue()
~~~~

I have not yet written any code in F# so debugging this is quite tough for me.
Hope its enough for you to go on :)
